Add react-navigation v3 to transformIgnorePatterns
Same as https://github.com/infinitered/jest-preset-ignite/pull/1, but for `react-navgation` v3.

>In v3, all of our main packages and repos are separated. There are the following core packages in our new NPM org:
> - @react-navigation/core - The primitives and utilities that define our patterns, plus several routers
> - @react-navigation/native - Container and support for navigators on React Native apps. createAppContainer from the main react-navigation package actually comes from this package.
> - @react-navigation/web - Web browser app container, and utilities for server rendering

Add `@react-navigation` to `transformIgnorePatterns` in `json-preset.json`
to resolve:

```
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React from 'react';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import
```